### ISSUE TITLE
array vs ArrayObject

### ISSUE THREAD

**Issue by tamagokun** [phpsgi/phpsgi#3]
Have you explored using php's ArrayObject rather than having to pass the `$env` array by reference? I used ArrayObject for rackem and it was nice not having to worry about a syntax detail to modify the environment. It just worked.

**Comment by c9s** [comment]
It looks good, however array object is not an array, so it can't work with
array functions. Middlewares using array functions will have to check the
variable type.

I am thinking about removing array type hinting to simplify the constraint,
so users want to modify environment variable can use pass by reference
prototype.   Applications can also use ArrayObject in the closure if it's
preferred. :)

Mike Kruk notifications@github.com 於 2015年9月29日 星期二寫道：

**Comment by tamagokun** [comment]
ahh, yes. somehow after all this time I guess I never found myself using array functions on $env. Good call though.

**Comment by tamagokun** [comment]
I'll close :)
